# Generated by Django 4.2 on 2023-06-17 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_company_facebook_company_instagram_company_linkedin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='tiktok',
            field=models.URLField(blank=True, null=True),
        ),
    ]
