# Generated by Django 4.2 on 2023-06-13 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
