# Generated by Django 4.2 on 2023-05-16 23:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_alter_job_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 5, 16, 23, 11, 3, 600163, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
