# Generated by Django 4.2 on 2023-06-13 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_job_required_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='required_skills',
        ),
    ]
