# Generated by Django 4.2 on 2023-06-23 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_remove_job_required_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
